############################
## CHANGE THESE
############################

baseURL: "https://tg.okolotattooing.ru/"
title: MAIN

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
