############################
## Author
############################

author:
  name: Main Tattoo
  image: author.png
  greeting: "Студия Татуировки Санкт-Петербург"
  icon: "🖤"

############################
## Links
############################

links:
  - website : https://okolotattooing.com/main-tattoo/
  - telegram: https://click.tgtrack.ru/22119d36b7d499?tag=nazhal

############################
## Colunms of Links
############################

monochrome: true

# between 2 & 6 columns are supported (both incl)
columns: 2

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: false

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: false

###############################
## OpenGraph & Twitter Cards
###############################

title: MAIN
description: "Студия Татуировки Санкт-Петербург"
images:
  - image.png

params:
  social_icons:
    - name: "vk"
      icon: "vk"
